### ISSUE TITLE
Creación de pantalla de Pumse

### ISSUE THREAD

**Issue by marqqitos** [facucompe/taekwongo-frontend#13]
- Título "Pumse"
- Botones para acceder a cada una de las 17 formas:
  - Al hacer click en un botón, se debe mostrar en una nueva pantalla como título la forma, la imagen asociada a la forma y en caso de existir, el video que muestra como se hace la forma.

**Comment by marcodicro** [comment]
Falta cargar la foto para cada pumse

**Comment by marcodicro** [comment]
Listo
