### ISSUE TITLE
Creación de pantalla de Vídeos de Técnica

### ISSUE THREAD

**Issue by marqqitos** [facucompe/taekwongo-frontend#14]
- Título "Vídeos de Técnica"
- Botones con cada una de las categorías (Ver Relevamiento)
  - Al acceder a cada categoría se mostrarán los vídeos asociados a la misma en una nueva pantalla con siendo su título la categoría de la técnica.
  - Un vídeo puede pertenecer a más de una categoría por lo que debe aparecer al acceder a cualquiera de ellas

**Comment by marcodicro** [comment]
Falta arreglar error al mostrar videos

**Comment by marcodicro** [comment]
Corregido
