### ISSUE TITLE
Registrar movimientos del entrenamiento

### ISSUE THREAD

**Issue by marqqitos** [facucompe/taekwongo-frontend#16]
Una vez realizada la conexión con la pulsera, el entrenamiento comienza y por cada registro que recibimos de la pulsera deberíamos mostrarlos en la pantalla en el orden en que nos llegan

- Debe haber un botón que diga "Detener" para parar el entrenamiento:
  - Cuando es presionado, se le debe permitir al usuario ver los movimientos registrados y descartar los que considere erróneos
  - Debe aparecer un botón guardar para registrar los movimientos
    - Cuando es presionado debe:
      - Generar el gráfico con los datos obtenidos
      - Mostrar las entradas con los movimientos registrados
      - Actualizar cual fue el mejor movimiento de la sesión si supera al previo

**Comment by marcodicro** [comment]
No estoy de acuerdo con el último bullet. El gráfico se muestra cuando el usuario toque un botón ejemplo Ver gráfico de progreso. Al guardar sólo se guardan los movimientos, no se muestra el gráfico

**Comment by marqqitos** [comment]
Yo digo que cuando guardas te lleve al menú donde tenés el registro con los movimientos y el gráfico.
Algo así: https://youtu.be/tIBiHDyev6w?t=40s

**Comment by marcodicro** [comment]
Ah ok no sabía que querían que el gráfico este visible todo el tiempo. Está bueno, puede ser

**Comment by marqqitos** [comment]
No se como lo queremos, a mi viendo eso me pareció que podía ser así, podemos actualizar el item a como lo queramos

**Comment by marcodicro** [comment]
Se registran los movimientos, se pide confirmación de lo medido y permite descartar algunos. Luego se guardan. No se muestra el grafico si el usuario no presiona Ver Progreso luego.
