### ISSUE TITLE
Agregar funcionalidad a la pantalla de Log In

### ISSUE THREAD

**Issue by marqqitos** [facucompe/taekwongo-frontend#4]
Al apretar el botón de "Iniciar Sesión":

- Validemos que los inputs tengan valores
- Se haga la llamada al backend para validar los datos
- En caso de inicio correcto redirigirlos a la pagina de entrenamientos
- En caso de errores mostrarlos por pantallas con un mensaje expresivo que no revele mucha información

Al apretar el botón de "Registrar":

- Pantalla con el formulario de registración
- Botón de "Registrarse"
- Botón de "Cancelar"

Al apretar el botón de "Olvidé mi contraseña"
- Solicitar nombre de usuario o email
- Enviar mail y empezar sistema de recupero de contraseña

**Comment by marcodicro** [comment]
Terminado
