### ISSUE TITLE
Creación de pantalla de Entrenamiento

### ISSUE THREAD

**Issue by marqqitos** [facucompe/taekwongo-frontend#6]
- Título “Entrenamiento”

- Botón para crear nuevo entrenamiento:
  - Al hacer click mostrar Pop up con:
    - Input para nombre
    - Elegir si es de velocidad o fuerza
    - Botón para guardar o cancelar
  - Al apretar “Guardar”:
    - Se cierra el Pop up
    - El entrenamiento figura en la pantalla
  - Al apretar “Cancelar”:
    - Se cierra el Pop up
    - El entrenamiento no se guarda

- Mostrar todos los entrenamientos existentes

**Comment by marcodicro** [comment]
El Cancelar es la flecha para atras
